### ISSUE TITLE
Move `typescript` from dependencies to devDependencies

### ISSUE THREAD

**Issue by SimonSchick** [highlight-run/react#10]
It's not imported by the code and should be moved.

**Comment by SimonSchick** [comment]
Also please remove `react-scripts` from deepDependencies since it causes *significant* installation bloat.

**Comment by Vadman97** [comment]
This was completed in #26 . Please use [@highlight.run/react@^1.2.0](https://www.npmjs.com/package/@highlight-run/react/v/1.2.0)
